<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 /home/sagar/sources/svelte/portfolio/static/bot.glb
Author: OSCAR CREATIVO (https://sketchfab.com/oscar_creativo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bot-neil-animation-by-oscar-creativo-56d5d623bb6c40faaa951aca02080510
Title: BOT NEIL ANIMATION By Oscar Creativo
-->

<script lang="ts">
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const gltf = useGltf('bot.glb')

  export const { actions, mixer } = useGltfAnimations<"NEIL ANIMATION">(gltf, ref)

  $effect(()=>{
    $actions['NEIL ANIMATION']?.play()
  })
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <T.Group
          name="0bc5cf2519344cae801272ca9df08433fbx"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group
                name="CUERPO"
                position={[0.73, -3.58, 0.27]}
              >
                <T.Group
                  name="ALA_IZQ"
                  position={[-40.1, 39.71, 1.92]}
                  rotation={[0, 0, 0.05]}
                >
                  <T.Mesh
                    name="ALA_IZQ_ALA_IZQ_0"
                    geometry={gltf.nodes.ALA_IZQ_ALA_IZQ_0.geometry}
                    material={gltf.materials.ALA_IZQ}
                  />
                </T.Group>
                <T.Group
                  name="ALA_DERE"
                  position={[42.58, 39.58, 2.28]}
                  rotation={[0, 0, 0.05]}
                >
                  <T.Mesh
                    name="ALA_DERE_ALA_DERE_0"
                    geometry={gltf.nodes.ALA_DERE_ALA_DERE_0.geometry}
                    material={gltf.materials.ALA_DERE}
                  />
                </T.Group>
                <T.Group
                  name="OJO"
                  position={[21.11, 46.37, 38.21]}
                >
                  <T.Mesh
                    name="OJO_OJO_0"
                    geometry={gltf.nodes.OJO_OJO_0.geometry}
                    material={gltf.materials.material}
                  />
                </T.Group>
                <T.Group
                  name="OJO_1"
                  position={[-21.26, 46.18, 39.35]}
                >
                  <T.Mesh
                    name="OJO_1_OJO_1_0"
                    geometry={gltf.nodes.OJO_1_OJO_1_0.geometry}
                    material={gltf.materials.OJO_1}
                  />
                </T.Group>
                <T.Group
                  name="CUEPRO"
                  position={[-2.32, 0.7, -0.27]}
                >
                  <T.Mesh
                    name="CUEPRO_CUEPRO_0"
                    geometry={gltf.nodes.CUEPRO_CUEPRO_0.geometry}
                    material={gltf.materials.CUEPRO}
                  />
                </T.Group>
              </T.Group>
              <T.Group
                name="PISO_RUEDA"
                position={[-0.77, -16.13, 0.31]}
              >
                <T.Mesh
                  name="PISO_RUEDA_PISO_RUEDA_0"
                  geometry={gltf.nodes.PISO_RUEDA_PISO_RUEDA_0.geometry}
                  material={gltf.materials.PISO_RUEDA}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
