<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 /home/sagar/sources/svelte/portfolio/static/robot_playground.glb
Author: Hadrien59 (https://sketchfab.com/Hadrien59)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-playground-59fc99d8dcb146f3a6c16dbbcc4680da
Title: Robot Playground
-->

<script lang="ts">
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const gltf = useGltf('robot_playground.glb')

  export const { actions, mixer } = useGltfAnimations<"Experiment">(gltf, ref)

  $effect(()=>{
    $actions['Experiment']?.play()
  })
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.06}
      >
        <T.Group
          name="000846fff9e546569ee038af7e24655afbx"
          rotation={[Math.PI / 2, 0, 0]}
        >
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group
                name="holo"
                scale={1.88}
              >
                <T.Group
                  name="group36"
                  position={[0.33, 0, -0.1]}
                  rotation={[-Math.PI, -0.14, -Math.PI]}
                  scale={0.99}
                >
                  <T.Group
                    name="group39"
                    rotation={[0, 0.88, 0]}
                  >
                    <T.Group
                      name="group37"
                      position={[-4.63, 14.29, 1.99]}
                    >
                      <T.Group
                        name="group31"
                        position={[4.63, -4.89, -1.99]}
                        rotation={[0.01, 0, 0.01]}
                        scale={1.18}
                      >
                        <T.Group
                          name="pPlatonic3"
                          position={[-0.35, -0.12, -0.32]}
                          scale={0}
                        >
                          <T.Mesh
                            name="pPlatonic3_holo1_0"
                            geometry={gltf.nodes.pPlatonic3_holo1_0.geometry}
                            material={gltf.materials.holo1}
                          />
                        </T.Group>
                        <T.Group
                          name="group35"
                          position={[0.22, 0.11, 0]}
                          rotation={[-Math.PI, -1.46, Math.PI]}
                        >
                          <T.Group
                            name="group38"
                            position={[0.04, 0.75, 0.25]}
                          >
                            <T.Group
                              name="group29"
                              position={[-0.03, -10.24, -0.04]}
                              rotation={[0, Math.PI / 4, 0]}
                            >
                              <T.Group
                                name="group21"
                                position={[-12.69, 10.7, 0]}
                                scale={0.24}
                              >
                                <T.Group
                                  name="MASH1_ReproMesh12"
                                  position={[0, 0.24, 0]}
                                  rotation={[-1.13, 0, Math.PI / 2]}
                                  scale={[1.03, 1, 1.03]}
                                >
                                  <T.Mesh
                                    name="MASH1_ReproMesh12_holo1_0"
                                    geometry={gltf.nodes.MASH1_ReproMesh12_holo1_0.geometry}
                                    material={gltf.materials.holo1}
                                  />
                                </T.Group>
                                <T.Group
                                  name="group14"
                                  rotation={[0, 1.13, 0]}
                                >
                                  <T.Group
                                    name="group30"
                                    rotation={[0.49, 0, 0]}
                                    scale={3.17}
                                  >
                                    <T.Group
                                      name="pSuperShape2"
                                      scale={2.08}
                                    >
                                      <T.Mesh
                                        name="pSuperShape2_holo1_0"
                                        geometry={gltf.nodes.pSuperShape2_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                    <T.Group
                                      name="pSuperShape3"
                                      scale={2.08}
                                    >
                                      <T.Mesh
                                        name="pSuperShape3_holo1_0"
                                        geometry={gltf.nodes.pSuperShape3_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                            </T.Group>
                            <T.Group
                              name="group28"
                              position={[-0.03, -10.24, -0.04]}
                              rotation={[0, Math.PI / 2, 0]}
                            >
                              <T.Group
                                name="group21_1"
                                position={[-12.69, 10.7, 0]}
                                scale={0.24}
                              >
                                <T.Group
                                  name="MASH1_ReproMesh12_1"
                                  position={[0, 0.24, 0]}
                                  rotation={[-1.13, 0, Math.PI / 2]}
                                  scale={[1.03, 1, 1.03]}
                                >
                                  <T.Group name="MASH1_ReproMesh19">
                                    <T.Mesh
                                      name="MASH1_ReproMesh19_holo1_0"
                                      geometry={gltf.nodes.MASH1_ReproMesh19_holo1_0.geometry}
                                      material={gltf.materials.holo1}
                                    />
                                  </T.Group>
                                </T.Group>
                                <T.Group
                                  name="group14_1"
                                  rotation={[0, 1.13, 0]}
                                >
                                  <T.Group
                                    name="group7"
                                    rotation={[0.32, -0.66, 1.52]}
                                    scale={2.05}
                                  >
                                    <T.Group name="pGear1">
                                      <T.Mesh
                                        name="pGear1_holo1_0"
                                        geometry={gltf.nodes.pGear1_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                    <T.Group name="pGear2">
                                      <T.Mesh
                                        name="pGear2_holo1_0"
                                        geometry={gltf.nodes.pGear2_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                            </T.Group>
                            <T.Group
                              name="group27"
                              position={[-0.03, -10.24, -0.04]}
                              rotation={[-Math.PI, Math.PI / 4, Math.PI]}
                            >
                              <T.Group
                                name="group20"
                                position={[-12.69, 10.7, 0]}
                                scale={0.24}
                              >
                                <T.Group
                                  name="MASH1_ReproMesh11"
                                  position={[0, 0.24, 0]}
                                  rotation={[-1.13, 0, Math.PI / 2]}
                                  scale={[1.03, 1, 1.03]}
                                >
                                  <T.Group name="MASH1_ReproMesh18">
                                    <T.Mesh
                                      name="MASH1_ReproMesh18_holo1_0"
                                      geometry={gltf.nodes.MASH1_ReproMesh18_holo1_0.geometry}
                                      material={gltf.materials.holo1}
                                    />
                                  </T.Group>
                                </T.Group>
                                <T.Group
                                  name="group13"
                                  rotation={[0, 1.13, 0]}
                                >
                                  <T.Group
                                    name="group6"
                                    position={[0, 0.03, 0]}
                                    rotation={[0.48, 0.1, 0]}
                                    scale={2.37}
                                  >
                                    <T.Group name="pHelix1">
                                      <T.Mesh
                                        name="pHelix1_holo1_0"
                                        geometry={gltf.nodes.pHelix1_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                    <T.Group name="pHelix2">
                                      <T.Mesh
                                        name="pHelix2_holo1_0"
                                        geometry={gltf.nodes.pHelix2_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                            </T.Group>
                            <T.Group
                              name="group26"
                              position={[-0.03, -10.24, -0.04]}
                              rotation={[-Math.PI, 0, -Math.PI]}
                            >
                              <T.Group
                                name="group19"
                                position={[-12.69, 10.7, 0]}
                                scale={0.24}
                              >
                                <T.Group
                                  name="MASH1_ReproMesh10"
                                  position={[0, 0.24, 0]}
                                  rotation={[-1.13, 0, Math.PI / 2]}
                                  scale={[1.03, 1, 1.03]}
                                >
                                  <T.Group name="MASH1_ReproMesh17">
                                    <T.Mesh
                                      name="MASH1_ReproMesh17_holo1_0"
                                      geometry={gltf.nodes.MASH1_ReproMesh17_holo1_0.geometry}
                                      material={gltf.materials.holo1}
                                    />
                                  </T.Group>
                                </T.Group>
                                <T.Group
                                  name="group12"
                                  rotation={[0, 1.13, 0]}
                                >
                                  <T.Group
                                    name="group4"
                                    position={[-0.25, 1.1, -0.4]}
                                    rotation={[-0.18, -0.67, 0.27]}
                                    scale={1.55}
                                  >
                                    <T.Group
                                      name="pPyramid1"
                                      scale={[5.26, 7.64, 5.26]}
                                    >
                                      <T.Mesh
                                        name="pPyramid1_holo1_0"
                                        geometry={gltf.nodes.pPyramid1_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                    <T.Group
                                      name="pPyramid2"
                                      scale={[5.57, 8.09, 5.57]}
                                    >
                                      <T.Mesh
                                        name="pPyramid2_holo1_0"
                                        geometry={gltf.nodes.pPyramid2_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                            </T.Group>
                            <T.Group
                              name="group25"
                              position={[-0.03, -10.24, -0.04]}
                              rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
                            >
                              <T.Group
                                name="group18"
                                position={[-12.69, 10.7, 0]}
                                scale={0.24}
                              >
                                <T.Group
                                  name="MASH1_ReproMesh9"
                                  position={[0, 0.24, 0]}
                                  rotation={[-1.13, 0, Math.PI / 2]}
                                  scale={[1.03, 1, 1.03]}
                                >
                                  <T.Group name="MASH1_ReproMesh16">
                                    <T.Mesh
                                      name="MASH1_ReproMesh16_holo1_0"
                                      geometry={gltf.nodes.MASH1_ReproMesh16_holo1_0.geometry}
                                      material={gltf.materials.holo1}
                                    />
                                  </T.Group>
                                </T.Group>
                                <T.Group
                                  name="group11"
                                  rotation={[0, 1.13, 0]}
                                >
                                  <T.Group
                                    name="group5"
                                    rotation={[0.22, 0.16, 0.93]}
                                    scale={1.89}
                                  >
                                    <T.Group name="pTorus2">
                                      <T.Mesh
                                        name="pTorus2_holo1_0"
                                        geometry={gltf.nodes.pTorus2_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                    <T.Group name="pTorus1">
                                      <T.Mesh
                                        name="pTorus1_holo1_0"
                                        geometry={gltf.nodes.pTorus1_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                            </T.Group>
                            <T.Group
                              name="group23"
                              position={[-0.03, -10.24, -0.04]}
                              rotation={[0, -Math.PI / 4, 0]}
                            >
                              <T.Group
                                name="group16"
                                position={[-12.69, 10.7, 0]}
                                scale={0.24}
                              >
                                <T.Group
                                  name="MASH1_ReproMesh7"
                                  position={[0, 0.24, 0]}
                                  rotation={[-1.13, 0, Math.PI / 2]}
                                  scale={[1.03, 1, 1.03]}
                                >
                                  <T.Group name="MASH1_ReproMesh14">
                                    <T.Mesh
                                      name="MASH1_ReproMesh14_holo1_0"
                                      geometry={gltf.nodes.MASH1_ReproMesh14_holo1_0.geometry}
                                      material={gltf.materials.holo1}
                                    />
                                  </T.Group>
                                </T.Group>
                                <T.Group
                                  name="group9"
                                  rotation={[0, 1.13, 0]}
                                  scale={1.3}
                                >
                                  <T.Group
                                    name="group2"
                                    rotation={[-0.62, -0.62, 0.1]}
                                  >
                                    <T.Group
                                      name="pCube1"
                                      scale={4.81}
                                    >
                                      <T.Mesh
                                        name="pCube1_holo1_0"
                                        geometry={gltf.nodes.pCube1_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                    <T.Group
                                      name="pCube2"
                                      scale={4.92}
                                    >
                                      <T.Mesh
                                        name="pCube2_holo1_0"
                                        geometry={gltf.nodes.pCube2_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                            </T.Group>
                            <T.Group
                              name="group22"
                              position={[-0.03, -10.24, -0.04]}
                            >
                              <T.Group
                                name="group15"
                                position={[-12.69, 10.7, 0]}
                                scale={0.24}
                              >
                                <T.Group
                                  name="MASH1_ReproMesh6"
                                  position={[0, 0.24, 0]}
                                  rotation={[-1.13, 0, Math.PI / 2]}
                                  scale={[1.03, 1, 1.03]}
                                >
                                  <T.Group name="MASH1_ReproMesh13">
                                    <T.Mesh
                                      name="MASH1_ReproMesh13_holo1_0"
                                      geometry={gltf.nodes.MASH1_ReproMesh13_holo1_0.geometry}
                                      material={gltf.materials.holo1}
                                    />
                                  </T.Group>
                                </T.Group>
                                <T.Group
                                  name="group8"
                                  rotation={[0, 1.13, 0]}
                                >
                                  <T.Group
                                    name="group1"
                                    rotation={[-0.51, 0, 0]}
                                    scale={[1.22, 0.98, 1.22]}
                                  >
                                    <T.Group
                                      name="pCylinder2"
                                      scale={3.57}
                                    >
                                      <T.Mesh
                                        name="pCylinder2_holo1_0"
                                        geometry={gltf.nodes.pCylinder2_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                    <T.Group
                                      name="pCylinder3"
                                      scale={3.67}
                                    >
                                      <T.Mesh
                                        name="pCylinder3_holo1_0"
                                        geometry={gltf.nodes.pCylinder3_holo1_0.geometry}
                                        material={gltf.materials.holo1}
                                      />
                                    </T.Group>
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                            </T.Group>
                            <T.Group
                              name="pCylinder4"
                              position={[-0.03, 0.46, -0.04]}
                              scale={[0.82, 0.44, 0.82]}
                            >
                              <T.Mesh
                                name="pCylinder4_holo1_0"
                                geometry={gltf.nodes.pCylinder4_holo1_0.geometry}
                                material={gltf.materials.holo1}
                              />
                            </T.Group>
                          </T.Group>
                          <T.Group
                            name="group24"
                            position={[0.02, -10.72, 0.22]}
                            rotation={[0, -Math.PI / 2, 0]}
                          >
                            <T.Group
                              name="group17"
                              position={[-12.36, 11.8, 0.23]}
                              scale={0.3}
                            >
                              <T.Group
                                name="group10"
                                rotation={[Math.PI, -1.16, Math.PI]}
                              >
                                <T.Group
                                  name="group3"
                                  scale={1.44}
                                >
                                  <T.Group
                                    name="pPlatonic1"
                                    scale={3.24}
                                  >
                                    <T.Mesh
                                      name="pPlatonic1_holo1_0"
                                      geometry={gltf.nodes.pPlatonic1_holo1_0.geometry}
                                      material={gltf.materials.holo1}
                                    />
                                  </T.Group>
                                  <T.Group
                                    name="pPlatonic2"
                                    scale={3.41}
                                  >
                                    <T.Mesh
                                      name="pPlatonic2_holo1_0"
                                      geometry={gltf.nodes.pPlatonic2_holo1_0.geometry}
                                      material={gltf.materials.holo1}
                                    />
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                              <T.Group
                                name="MASH1_ReproMesh8"
                                position={[0.23, 0.01, -0.55]}
                                rotation={[-1.13, 0, Math.PI / 2]}
                                scale={[0.82, 0.79, 0.82]}
                              >
                                <T.Group name="MASH1_ReproMesh15">
                                  <T.Mesh
                                    name="MASH1_ReproMesh15_holo1_0"
                                    geometry={gltf.nodes.MASH1_ReproMesh15_holo1_0.geometry}
                                    material={gltf.materials.holo1}
                                  />
                                </T.Group>
                              </T.Group>
                            </T.Group>
                          </T.Group>
                        </T.Group>
                      </T.Group>
                    </T.Group>
                  </T.Group>
                </T.Group>
                <T.Group
                  name="ground"
                  position={[0, 0.39, 0]}
                >
                  <T.Group
                    name="pPipe4"
                    position={[0, -0.43, 0]}
                    rotation={[0, -0.31, 0]}
                  >
                    <T.Group
                      name="MASH1_ReproMesh2"
                      position={[0, 0.43, 0]}
                    >
                      <T.Mesh
                        name="MASH1_ReproMesh2_holo1_0"
                        geometry={gltf.nodes.MASH1_ReproMesh2_holo1_0.geometry}
                        material={gltf.materials.holo1}
                      />
                    </T.Group>
                    <T.Mesh
                      name="pPipe4_holo1_0"
                      geometry={gltf.nodes.pPipe4_holo1_0.geometry}
                      material={gltf.materials.holo1}
                    />
                  </T.Group>
                  <T.Group
                    name="pPipe2"
                    position={[0, -0.58, 0]}
                    rotation={[0, 0.31, 0]}
                  >
                    <T.Group
                      name="MASH1_ReproMesh3"
                      position={[0, 0.58, 0]}
                      scale={[0.82, 0.8, 0.82]}
                    >
                      <T.Mesh
                        name="MASH1_ReproMesh3_holo1_0"
                        geometry={gltf.nodes.MASH1_ReproMesh3_holo1_0.geometry}
                        material={gltf.materials.holo1}
                      />
                    </T.Group>
                    <T.Group
                      name="pPipe3"
                      rotation={[0, 0.68, 0]}
                      scale={0.86}
                    >
                      <T.Mesh
                        name="pPipe3_holo1_0"
                        geometry={gltf.nodes.pPipe3_holo1_0.geometry}
                        material={gltf.materials.holo1}
                      />
                    </T.Group>
                    <T.Mesh
                      name="pPipe2_holo1_0"
                      geometry={gltf.nodes.pPipe2_holo1_0.geometry}
                      material={gltf.materials.holo1}
                    />
                  </T.Group>
                  <T.Group
                    name="pPipe1"
                    rotation={[0, -0.31, 0]}
                  >
                    <T.Group
                      name="MASH1_ReproMesh1"
                      scale={[1.03, 1, 1.03]}
                    >
                      <T.Mesh
                        name="MASH1_ReproMesh1_holo1_0"
                        geometry={gltf.nodes.MASH1_ReproMesh1_holo1_0.geometry}
                        material={gltf.materials.holo1}
                      />
                    </T.Group>
                    <T.Mesh
                      name="pPipe1_holo1_0"
                      geometry={gltf.nodes.pPipe1_holo1_0.geometry}
                      material={gltf.materials.holo1}
                    />
                  </T.Group>
                  <T.Group
                    name="pDisc1"
                    position={[0, -0.39, 0]}
                    scale={11.11}
                  >
                    <T.Mesh
                      name="pDisc1_holo1_0"
                      geometry={gltf.nodes.pDisc1_holo1_0.geometry}
                      material={gltf.materials.holo1}
                    />
                  </T.Group>
                </T.Group>
              </T.Group>
              <T.Group name="bot_geo">
                <T.Group name="knee" />
                <T.Group name="foot" />
                <T.Group name="hand" />
                <T.Group name="upperLeg" />
                <T.Group name="body" />
                <T.Group name="index" />
                <T.Group name="pinky" />
                <T.Group name="thumb" />
                <T.Group name="earBall" />
                <T.Group name="topHeadBall" />
                <T.Group name="topHeadTube" />
                <T.Group name="shoulder" />
                <T.Group name="midfinger" />
                <T.Group name="neckTop" />
                <T.Group name="neck" />
                <T.Group name="head" />
                <T.Group name="topHead" />
                <T.Group name="hip" />
                <T.Group name="earTube" />
                <T.Group name="ear" />
                <T.Group name="neckBase" />
                <T.Group name="face">
                  <T.Group
                    name="eyeCloseKawaii"
                    position={[-13.61, -3.32, -2.9]}
                    scale={1.29}
                  />
                  <T.Group
                    name="eye"
                    position={[0.41, -4.26, -1.92]}
                    scale={1.16}
                  />
                  <T.Group
                    name="eyeSmile"
                    position={[-13.48, -3.21, -2.25]}
                    scale={1.15}
                  />
                  <T.Group
                    name="eyeClose"
                    position={[-16, 1.37, -1.5]}
                  />
                  <T.Group
                    name="happy"
                    position={[-13.39, -0.05, -1.52]}
                  />
                  <T.Group
                    name="smile"
                    position={[0, 0, -1.52]}
                  />
                  <T.Group
                    name="o"
                    position={[-13.39, 1.37, -1.25]}
                  />
                  <T.Group
                    name="close"
                    position={[-13.39, -0.04, -1.52]}
                  />
                  <T.Group
                    name="group34"
                    rotation={[-Math.PI, 0, 0]}
                    scale={-1}
                  >
                    <T.Group
                      name="eyeCloseKawaii1"
                      position={[-13.61, -3.32, -2.9]}
                      scale={1.29}
                    />
                    <T.Group
                      name="eye1"
                      position={[-5.68, -4.26, -1.92]}
                      rotation={[-Math.PI, 0, 0]}
                      scale={[-1.15, -1.16, -1.16]}
                    />
                    <T.Group
                      name="eyeSmile1"
                      position={[-13.48, -3.21, -2.25]}
                      scale={1.15}
                    />
                    <T.Group
                      name="eyeClose1"
                      position={[-16, 1.37, -1.5]}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="arm2" />
              </T.Group>
              <T.Group name="Group">
                <T.Group name="Main">
                  <T.Group name="DeformationSystem">
                    <T.Group name="Object_159">
                      <T is={gltf.nodes._rootJoint} />
                      <T.Group name="Object_161" />
                      <T.Group name="Object_163" />
                      <T.Group name="Object_165" />
                      <T.Group name="Object_167" />
                      <T.Group name="Object_169" />
                      <T.Group name="Object_171" />
                      <T.Group name="Object_173" />
                      <T.Group name="Object_175" />
                      <T.Group name="Object_177" />
                      <T.Group name="Object_179" />
                      <T.Group name="Object_181" />
                      <T.Group name="Object_183" />
                      <T.Group name="Object_185" />
                      <T.Group name="Object_187" />
                      <T.Group name="Object_189" />
                      <T.Group name="Object_191" />
                      <T.Group name="Object_193" />
                      <T.Group name="Object_195" />
                      <T.Group name="Object_197" />
                      <T.Group name="Object_199" />
                      <T.Group name="Object_201" />
                      <T.Group
                        name="Object_203"
                        position={[-13.61, -3.32, -2.9]}
                        scale={1.29}
                      />
                      <T.Group
                        name="Object_205"
                        position={[0.41, -4.26, -1.92]}
                        scale={1.16}
                      />
                      <T.Group
                        name="Object_207"
                        position={[-13.48, -3.21, -2.25]}
                        scale={1.15}
                      />
                      <T.Group
                        name="Object_209"
                        position={[-16, 1.37, -1.5]}
                      />
                      <T.Group
                        name="Object_211"
                        position={[-13.39, -0.05, -1.52]}
                      />
                      <T.Group
                        name="Object_213"
                        position={[0, 0, -1.52]}
                      />
                      <T.Group
                        name="Object_215"
                        position={[-13.39, 1.37, -1.25]}
                      />
                      <T.Group
                        name="Object_217"
                        position={[-13.39, -0.04, -1.52]}
                      />
                      <T.Group
                        name="Object_219"
                        position={[13.61, -3.32, -2.9]}
                        scale={[-1.29, 1.29, 1.29]}
                      />
                      <T.Group
                        name="Object_221"
                        position={[5.68, -4.26, -1.92]}
                        scale={1.16}
                      />
                      <T.Group
                        name="Object_223"
                        position={[13.48, -3.21, -2.25]}
                        scale={[-1.15, 1.15, 1.15]}
                      />
                      <T.Group
                        name="Object_225"
                        position={[16, 1.37, -1.5]}
                        scale={[-1, 1, 1]}
                      />
                      <T.Group name="Object_227" />
                      <T.SkinnedMesh
                        name="Object_162"
                        geometry={gltf.nodes.Object_162.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_162.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_164"
                        geometry={gltf.nodes.Object_164.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_164.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_166"
                        geometry={gltf.nodes.Object_166.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_166.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_168"
                        geometry={gltf.nodes.Object_168.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_168.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_170"
                        geometry={gltf.nodes.Object_170.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_170.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_172"
                        geometry={gltf.nodes.Object_172.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_172.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_174"
                        geometry={gltf.nodes.Object_174.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_174.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_176"
                        geometry={gltf.nodes.Object_176.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_176.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_178"
                        geometry={gltf.nodes.Object_178.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_178.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_180"
                        geometry={gltf.nodes.Object_180.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_180.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_182"
                        geometry={gltf.nodes.Object_182.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_182.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_184"
                        geometry={gltf.nodes.Object_184.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_184.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_186"
                        geometry={gltf.nodes.Object_186.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_186.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_188"
                        geometry={gltf.nodes.Object_188.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_188.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_190"
                        geometry={gltf.nodes.Object_190.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_190.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_192"
                        geometry={gltf.nodes.Object_192.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_192.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_194"
                        geometry={gltf.nodes.Object_194.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_194.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_196"
                        geometry={gltf.nodes.Object_196.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_196.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_198"
                        geometry={gltf.nodes.Object_198.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_198.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_200"
                        geometry={gltf.nodes.Object_200.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_200.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_202"
                        geometry={gltf.nodes.Object_202.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_202.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_204"
                        geometry={gltf.nodes.Object_204.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_204.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_206"
                        geometry={gltf.nodes.Object_206.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_206.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_208"
                        geometry={gltf.nodes.Object_208.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_208.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_210"
                        geometry={gltf.nodes.Object_210.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_210.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_212"
                        geometry={gltf.nodes.Object_212.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_212.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_214"
                        geometry={gltf.nodes.Object_214.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_214.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_216"
                        geometry={gltf.nodes.Object_216.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_216.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_218"
                        geometry={gltf.nodes.Object_218.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_218.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_220"
                        geometry={gltf.nodes.Object_220.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_220.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_222"
                        geometry={gltf.nodes.Object_222.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_222.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_224"
                        geometry={gltf.nodes.Object_224.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_224.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_226"
                        geometry={gltf.nodes.Object_226.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_226.skeleton}
                      />
                      <T.SkinnedMesh
                        name="Object_228"
                        geometry={gltf.nodes.Object_228.geometry}
                        material={gltf.materials.material}
                        skeleton={gltf.nodes.Object_228.skeleton}
                      />
                    </T.Group>
                  </T.Group>
                </T.Group>
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
