<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 /home/sagar/sources/svelte/portfolio/static/robot_playground.glb
Author: Hadrien59 (https://sketchfab.com/Hadrien59)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-playground-59fc99d8dcb146f3a6c16dbbcc4680da
Title: Robot Playground
-->

<script  lang="ts">


  import {GLTF,useGltfAnimations} from '@threlte/extras'



  const { gltf, actions } = useGltfAnimations<'Experiment'>()


  $effect(()=>{
      $actions['Experiment']?.play()
  })
</script>
<GLTF url={'robot_playground.glb'} bind:gltf={$gltf} />